### PR TITLE
hierarchical (bayes?) scoring

### PR DESCRIPTION
**Pull request by schuyler1d**
ordering supporting/counter links based on their own supporting/counter arguments.

As my TODO comment says, I'm not sure we want to deploy this directly yet, since it doesn't actually weight by a point's own relevancy at all anymore.

### CODE REVIEW

**Comment by aaronlifshin** [comment]
Thanks for this, great start!

This is probably going to work, but you have to be careful here and avoid loops if you go one more level down.  Even this, as is, should really check if the point is linked to itself to avoid some nasty infinite loop and a lot of App Engine instance charges.

**Comment by schuyler1d** [comment]
Todo:
 - [ ] x
 - [ ] x
 - [ ] x
 - [ ] x

**Comment by schuyler1d** [comment]
Ok, so I tested this and it's working.  Some notes:
* The current change adds a user-facing "score" which maps to Point.pointValue() and is my measurement of how "good" a point is.  See the code comments for details but it adds a point if there's a source/citation, it adds points for upvotes - down votes, and it gathers sums child points with upvotes >= dwnvotes with supporting - counter. It excludes over-downvoted points because the "value" of a point shouldn't weigh in that other people have added bad arguments.
* The user facing score is next to relevancy. It could probably use some design help but we can also just hide it for now.
* Sorting is first by relevancy and then by point value

Happy to talk through the decisions next steps here

**Comment by travis** [comment]
This looks great! 

It would be super useful for me to see some test cases exercising and demonstrating the scoring functionality here. It looks like we aren't using a unit testing library right now (does that sound right @aaronlifshin and @ebyrne?) so I'll add a test library investigation to my TODO list. 

Having some test cases will be useful for this conversation, are a prerequisite to me being comfortable merging this code, and are something I would expect you to write @schuyler1d as the domain expert on this scoring system (ie, I'm not comfortable writing tests cases for something like this) so it might be helpful to chat on the phone this week - @schuyler1d do you have any availability on Thursday or Friday?

**Comment by aaronlifshin** [comment]
That is correct, there have not been any unit tests or test lib integrtaion
in the past.

**Comment by ebyrne** [comment]
In point.py, getChildrenPointRating it looks like the second iterator is referencing the wrong variable:

        return int(round((sum([((sp.upVotes - sp.downVotes) or 1) * (sp._linkInfo.rating / 100.0)
                               for sp in supportingPoints
                               if sp.upVotes >= sp.downVotes])
                          - abs(sum([((cp.upVotes - sp.downVotes) or 1) * (sp._linkInfo.rating / 100.0)
                                     for cp in counterPoints
                                     if cp.upVotes >= cp.downVotes])))))

It should be cp for the two sp instances in the second term correct?

**Comment by ebyrne** [comment]
Added another update to fix some of the inconsistencies from testing.  Let me know if you disagree with anything and happy to modify/revert.  Will deploy this to staging otherwise.

**Pull request merged**
