### PR TITLE
Sort relevant cards by relevance

### PR DESCRIPTION
**Pull request by travis**

### CODE REVIEW

**Comment by justlikeUNIBLAB** [comment]
merge away

**Comment by justlikeUNIBLAB** [comment]
not sure what I should be looking at on this one. looks to me like the list of SPs and CPs both sort by relevance, but I'm not seeing the "interweave" feed yet. is that expected?

**Comment by travis** [comment]
hm, it was working for me... could you paste a screenshot of how your stuff looks on a mobile-sized browser? you can use the chrome devtools to simulate a mobile-sized screen for convenience.

**Comment by justlikeUNIBLAB** [comment]
Ah! I assumed it would occur based on window width, but you've implemented based on device width (so this effect only occurs on mobile). It's easy enough for me to switch that up with this nifty react-responsive library you've installed.

Fun things about basing on window width: 
- on mobile, for larger devices rotating to landscape will expand to multi-column (and vice-versa)
- on desktop, small monitors/windows get the benefit of the interweave

Any factors I'm not seeing / reasons why I shouldn't proceed?

**Pull request merged**
